/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { OwnerManagerContract } from "./OwnerManager";
import { InheritanceModuleContract } from "./InheritanceModule";
import { GnosisSafeContract } from "./GnosisSafe";
import { MigrationsContract } from "./Migrations";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "OwnerManager"): OwnerManagerContract;
      require(name: "InheritanceModule"): InheritanceModuleContract;
      require(name: "GnosisSafe"): GnosisSafeContract;
      require(name: "Migrations"): MigrationsContract;
    }
  }
}

export { OwnerManagerContract, OwnerManagerInstance } from "./OwnerManager";
export {
  InheritanceModuleContract,
  InheritanceModuleInstance,
} from "./InheritanceModule";
export { GnosisSafeContract, GnosisSafeInstance } from "./GnosisSafe";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
