/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface InheritanceModuleContract
  extends Truffle.Contract<InheritanceModuleInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<InheritanceModuleInstance>;
}

export interface AddedOwner {
  name: "AddedOwner";
  args: {
    owner: string;
    0: string;
  };
}

export interface ChangedThreshold {
  name: "ChangedThreshold";
  args: {
    threshold: BN;
    0: BN;
  };
}

export interface RemovedOwner {
  name: "RemovedOwner";
  args: {
    owner: string;
    0: string;
  };
}

type AllEvents = AddedOwner | ChangedThreshold | RemovedOwner;

export interface InheritanceModuleInstance extends Truffle.ContractInstance {
  ALLOWANCE_TRANSFER_TYPEHASH(
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  DOMAIN_SEPARATOR_TYPEHASH(
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  NAME(txDetails?: Truffle.TransactionDetails): Promise<string>;

  VERSION(txDetails?: Truffle.TransactionDetails): Promise<string>;

  addOwnerWithThreshold: {
    (
      owner: string,
      _threshold: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      owner: string,
      _threshold: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      owner: string,
      _threshold: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      owner: string,
      _threshold: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  changeThreshold: {
    (
      _threshold: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _threshold: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _threshold: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _threshold: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  getDataHash(
    data: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  getOwners(txDetails?: Truffle.TransactionDetails): Promise<string[]>;

  getThreshold(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  inherit: {
    (
      safe: string,
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      safe: string,
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      safe: string,
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      safe: string,
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  inheritants(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  isExecuted(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  isInheritant(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  isOwner(
    owner: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  reconfigure: {
    (_inheritants: string[], txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _inheritants: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _inheritants: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _inheritants: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  removeInheritance: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  removeOwner: {
    (
      prevOwner: string,
      owner: string,
      _threshold: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      prevOwner: string,
      owner: string,
      _threshold: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      prevOwner: string,
      owner: string,
      _threshold: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      prevOwner: string,
      owner: string,
      _threshold: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  setup: {
    (_inheritants: string[], txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _inheritants: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _inheritants: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _inheritants: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  swapOwner: {
    (
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      prevOwner: string,
      oldOwner: string,
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    ALLOWANCE_TRANSFER_TYPEHASH(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    DOMAIN_SEPARATOR_TYPEHASH(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    NAME(txDetails?: Truffle.TransactionDetails): Promise<string>;

    VERSION(txDetails?: Truffle.TransactionDetails): Promise<string>;

    addOwnerWithThreshold: {
      (
        owner: string,
        _threshold: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        owner: string,
        _threshold: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        owner: string,
        _threshold: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        owner: string,
        _threshold: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    changeThreshold: {
      (
        _threshold: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _threshold: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _threshold: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _threshold: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    getDataHash(
      data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    getOwners(txDetails?: Truffle.TransactionDetails): Promise<string[]>;

    getThreshold(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    inherit: {
      (
        safe: string,
        prevOwner: string,
        oldOwner: string,
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        safe: string,
        prevOwner: string,
        oldOwner: string,
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        safe: string,
        prevOwner: string,
        oldOwner: string,
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        safe: string,
        prevOwner: string,
        oldOwner: string,
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    inheritants(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    isExecuted(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    isInheritant(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    isOwner(
      owner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    reconfigure: {
      (_inheritants: string[], txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _inheritants: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _inheritants: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _inheritants: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    removeInheritance: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    removeOwner: {
      (
        prevOwner: string,
        owner: string,
        _threshold: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        prevOwner: string,
        owner: string,
        _threshold: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        prevOwner: string,
        owner: string,
        _threshold: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        prevOwner: string,
        owner: string,
        _threshold: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    setup: {
      (_inheritants: string[], txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _inheritants: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _inheritants: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _inheritants: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    swapOwner: {
      (
        prevOwner: string,
        oldOwner: string,
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        prevOwner: string,
        oldOwner: string,
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        prevOwner: string,
        oldOwner: string,
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        prevOwner: string,
        oldOwner: string,
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
